#docker run -d --name myelastic --hostname myelastic myelastic
FROM elasticsearch
 
#Delete the Existing default.conf
#RUN curl -XPUT 'http://localhost:9200/myindex' -d "{  "mappings": {    "my_type": {      "properties": {        "date": {          "type": "date"         }      }    }  }}"
