version: '2'

services:
   loadbalancer: 
     build: ./loadbalancer
     container_name: loadbalancer
     depends_on: 
       - myapp1
       - myapp2
     hostname: loadbalancer
     links: 
       - myapp1
       - myapp2
     ports: 
       - "80:80"
   myapp1: 
     build: ./apache
     container_name: myapp1
     depends_on: 
       - mylogstash
       - myfpm
     hostname: myapp1
     links: 
       - myredis
       - mylogstash
   myapp2: 
     build: ./apache
     container_name: myapp2
     depends_on: 
       - mylogstash
       - myfpm
     hostname: myapp2
     links: 
       - myredis
       - mylogstash
   myelastic: 
     build: ./elastic
     container_name: myelastic
     hostname: myelastic
   myfpm: 
     build: ./php-fpm
     container_name: myfpm
     depends_on: 
       - myredis
       - mylogstash
     hostname: myfpm
     links: 
       - myredis
       - mylogstash
   mykibana: 
     build: ./kibana
     container_name: mykibana
     depends_on: 
       - myelastic
     hostname: mykibana
     links: 
       - myelastic
     ports: 
       - "5777:5777"
   mylogstash: 
     build: ./logstash
     container_name: mylogstash
     depends_on: 
       - myelastic
     hostname: mylogstash
     links: 
       - myelastic
   myredis: 
     build: ./redis
     container_name: myredis
     hostname: myredis
